// Unified theme styles for Trace It
export const S = {
  app: {
    minHeight: "100vh",
    background: "#0f0f0f",
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    color: "#f0ede8",
  },
  navbar: {
    background: "#0f0f0f",
    borderBottom: "1px solid #1e1e1e",
    padding: "0 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 58,
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontWeight: 700,
    fontSize: 17,
    color: "#f0ede8",
    cursor: "pointer",
    letterSpacing: "-0.3px",
  },
  logoDot: { width: 8, height: 8, borderRadius: "50%", background: "#e8533a" },
  navActions: { display: "flex", alignItems: "center", gap: 8 },
  btnPrimary: {
    background: "#e8533a",
    color: "#fff",
    border: "none",
    padding: "7px 16px",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    transition: "opacity .15s",
  },
  btnSecondary: {
    background: "transparent",
    color: "#f0ede8",
    border: "1px solid #2a2a2a",
    padding: "7px 14px",
    borderRadius: 8,
    fontSize: 13,
    cursor: "pointer",
  },
  btnGhost: {
    background: "transparent",
    color: "#888",
    border: "none",
    padding: "6px 10px",
    borderRadius: 6,
    fontSize: 13,
    cursor: "pointer",
  },
  main: { maxWidth: 1100, margin: "0 auto", padding: "28px 20px" },
  hero: { marginBottom: 28 },
  heroTitle: { fontSize: 28, fontWeight: 700, letterSpacing: "-0.6px", margin: "0 0 6px", color: "#f0ede8" },
  heroSub: { fontSize: 14, color: "#666", margin: 0 },
  searchRow: {
    display: "flex",
    gap: 10,
    marginBottom: 18,
    flexWrap: "wrap",
  },
  searchInput: {
    flex: 1,
    minWidth: 200,
    background: "#161616",
    border: "1px solid #222",
    color: "#f0ede8",
    padding: "9px 14px",
    borderRadius: 9,
    fontSize: 14,
    outline: "none",
  },
  select: {
    background: "#161616",
    border: "1px solid #222",
    color: "#999",
    padding: "9px 12px",
    borderRadius: 9,
    fontSize: 13,
    cursor: "pointer",
    outline: "none",
  },
  tabRow: { display: "flex", gap: 4, marginBottom: 20 },
  tabActive: {
    background: "#f0ede8",
    color: "#0f0f0f",
    border: "none",
    padding: "7px 18px",
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  tabInactive: {
    background: "transparent",
    color: "#555",
    border: "1px solid #222",
    padding: "7px 18px",
    borderRadius: 7,
    fontSize: 13,
    cursor: "pointer",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(290px, 1fr))",
    gap: 14,
  },
  card: {
    background: "#141414",
    border: "1px solid #1e1e1e",
    borderRadius: 14,
    padding: "16px 18px",
    cursor: "pointer",
    transition: "border-color .15s, transform .15s",
    position: "relative",
  },
  cardTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 },
  cardTitle: { fontSize: 15, fontWeight: 600, color: "#f0ede8", margin: "0 0 4px", lineHeight: 1.3 },
  cardDesc: { fontSize: 12, color: "#666", lineHeight: 1.5, margin: 0 },
  // badge is a function — no type annotation needed in plain JS
  badge: (type) => ({
    background: type === "found" ? "#1a2e1a" : "#2a1818",
    color: type === "found" ? "#5acc6a" : "#e8533a",
    fontSize: 10,
    fontWeight: 700,
    padding: "3px 8px",
    borderRadius: 5,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  }),
  cardMeta: { display: "flex", gap: 10, marginTop: 12, flexWrap: "wrap" },
  metaChip: {
    fontSize: 11,
    color: "#555",
    background: "#1a1a1a",
    padding: "3px 8px",
    borderRadius: 5,
  },
  resolvedOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(15,15,15,0.7)",
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    color: "#444",
    fontWeight: 600,
    letterSpacing: "0.08em",
  },
  emptyState: {
    textAlign: "center",
    padding: "60px 20px",
    color: "#444",
  },
  modal: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.75)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 200,
    padding: 20,
  },
  modalBox: {
    background: "#141414",
    border: "1px solid #222",
    borderRadius: 16,
    padding: "28px 28px 24px",
    width: "100%",
    maxWidth: 600,
    maxHeight: "90vh",
    overflowY: "auto",
  },
  modalTitle: { fontSize: 18, fontWeight: 700, margin: "0 0 20px", color: "#f0ede8" },
  formRow: { marginBottom: 14 },
  label: { display: "block", fontSize: 12, color: "#666", marginBottom: 5, fontWeight: 500 },
  input: {
    width: "100%",
    background: "#0f0f0f",
    border: "1px solid #222",
    color: "#f0ede8",
    padding: "9px 12px",
    borderRadius: 8,
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    background: "#0f0f0f",
    border: "1px solid #222",
    color: "#f0ede8",
    padding: "9px 12px",
    borderRadius: 8,
    fontSize: 13,
    outline: "none",
    resize: "vertical",
    minHeight: 80,
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  formSelect: {
    width: "100%",
    background: "#0f0f0f",
    border: "1px solid #222",
    color: "#f0ede8",
    padding: "9px 12px",
    borderRadius: 8,
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box",
  },
  detailModal: {
    background: "#141414",
    border: "1px solid #222",
    borderRadius: 16,
    padding: "28px",
    width: "100%",
    maxWidth: 520,
    maxHeight: "90vh",
    overflowY: "auto",
  },
  authBox: {
    minHeight: "100vh",
    background: "#0f0f0f",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  authCard: {
    background: "#141414",
    border: "1px solid #1e1e1e",
    borderRadius: 18,
    padding: "36px 32px",
    width: "100%",
    maxWidth: 380,
  },
  authTitle: { fontSize: 22, fontWeight: 700, margin: "0 0 4px", color: "#f0ede8" },
  authSub: { fontSize: 13, color: "#555", margin: "0 0 24px" },
  divider: { borderColor: "#1e1e1e", margin: "18px 0" },
  statsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 10,
    marginBottom: 24,
  },
  statCard: {
    background: "#141414",
    border: "1px solid #1e1e1e",
    borderRadius: 10,
    padding: "14px 16px",
  },
  statNum: { fontSize: 24, fontWeight: 700, color: "#f0ede8", lineHeight: 1 },
  statLabel: { fontSize: 11, color: "#555", marginTop: 4 },
  footer: {
    background: "#0f0f0f",
    borderTop: "1px solid #1e1e1e",
    padding: "24px",
    textAlign: "center",
    fontSize: 12,
    color: "#555",
  },
};